INSERT INTO TIPO_USUARIO VALUES(1L, 'Administrador', 1);
INSERT INTO TIPO_USUARIO VALUES(2L, 'Comum', 2);
INSERT INTO TIPO_SEGURO VALUES(1L, 'Automovel');
INSERT INTO TIPO_SEGURO VALUES(2L, 'Residencial');
INSERT INTO TIPO_SEGURO VALUES(3L, 'Vida');

ALTER TABLE CONTATO_CLIENTE DROP CONSTRAINT FKMLJ74NMMYGPMGO36H3ACSUJXA;

ALTER TABLE CONTATO_CLIENTE
ADD CONSTRAINT FKMLJ74NMMYGPMGO36H3ACSUJXA
FOREIGN KEY (CLIENTE_ID)
REFERENCES CLIENTE (ID)
ON DELETE CASCADE;

ALTER TABLE VEICULO DROP CONSTRAINT FKHV6I4HAQL7SMQ06H00DBL4C3V;

ALTER TABLE VEICULO
ADD CONSTRAINT FKHV6I4HAQL7SMQ06H00DBL4C3V
FOREIGN KEY (SEGURO_ID)
REFERENCES SEGURO (ID)
ON DELETE CASCADE;

ALTER TABLE IMOVEL DROP CONSTRAINT FKKBNWC2KPPF2MTC7X721SJR171;

ALTER TABLE IMOVEL
ADD CONSTRAINT FKKBNWC2KPPF2MTC7X721SJR171
FOREIGN KEY (SEGURO_ID)
REFERENCES SEGURO (ID)
ON DELETE CASCADE;

ALTER TABLE VIDA DROP CONSTRAINT FK45COAWN4HHFB2IL381IIOQITR;

ALTER TABLE VIDA
ADD CONSTRAINT FK45COAWN4HHFB2IL381IIOQITR
FOREIGN KEY (SEGURO_ID)
REFERENCES SEGURO (ID)
ON DELETE CASCADE;