INSERT INTO TIPO_USUARIO VALUES(1L, 'Administrador', 1);
INSERT INTO TIPO_USUARIO VALUES(2L, 'Comum', 2);
INSERT INTO TIPO_SEGURO VALUES(1L, 'Automovel');
INSERT INTO TIPO_SEGURO VALUES(2L, 'Residencial');
INSERT INTO TIPO_SEGURO VALUES(3L, 'Vida');